/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package innovationlab.djp_tst2_0_1;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class row1Struct extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord, java.io.Serializable {
  /** Default serial version UID. */
  public static final int serialVersionUID = 1;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"row1Struct\",\"namespace\":\"innovationlab.djp_tst2_0_1\",\"fields\":[{\"name\":\"name\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\",\"java-class\":\"java.lang.String\"},\"null\"]},{\"name\":\"id\",\"type\":[\"int\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
   public java.lang.String name;
   public java.lang.Integer id;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.String)value$; break;
    case 1: id = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /** Creates a new row1Struct RecordBuilder */
  public static innovationlab.djp_tst2_0_1.row1Struct.Builder newBuilder() {
    return new innovationlab.djp_tst2_0_1.row1Struct.Builder();
  }
  
  /** Creates a new row1Struct RecordBuilder by copying an existing Builder */
  public static innovationlab.djp_tst2_0_1.row1Struct.Builder newBuilder(innovationlab.djp_tst2_0_1.row1Struct.Builder other) {
    return new innovationlab.djp_tst2_0_1.row1Struct.Builder(other);
  }
  
  /** Creates a new row1Struct RecordBuilder by copying an existing row1Struct instance */
  public static innovationlab.djp_tst2_0_1.row1Struct.Builder newBuilder(innovationlab.djp_tst2_0_1.row1Struct other) {
    return new innovationlab.djp_tst2_0_1.row1Struct.Builder(other);
  }
  
  /**
   * RecordBuilder for row1Struct instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<row1Struct>
    implements org.apache.avro.data.RecordBuilder<row1Struct> {

    private java.lang.String name;
    private java.lang.Integer id;

    /** Creates a new Builder */
    private Builder() {
      super(innovationlab.djp_tst2_0_1.row1Struct.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(innovationlab.djp_tst2_0_1.row1Struct.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing row1Struct instance */
    private Builder(innovationlab.djp_tst2_0_1.row1Struct other) {
            super(innovationlab.djp_tst2_0_1.row1Struct.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.String getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public innovationlab.djp_tst2_0_1.row1Struct.Builder setName(java.lang.String value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public innovationlab.djp_tst2_0_1.row1Struct.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public innovationlab.djp_tst2_0_1.row1Struct.Builder setId(java.lang.Integer value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'id' field */
    public innovationlab.djp_tst2_0_1.row1Struct.Builder clearId() {
      id = null;
      fieldSetFlags()[1] = false;
      return this;
    }


    public row1Struct build() {
      try {
        row1Struct record = new row1Struct();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.String) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}